introduction/overview.md
specified staticframesize as 6 to account for the "Hello0" string.
=> Corrected example code for ragg2

esil.md
When I was going to add the PICK/RPICK operations I saw that some ops were not documented. I have included them in this edit (TODO, BREAK, CLEAR, DUP, SWAP, ...)
=> Added info about undocumented ESIL operations

crackmes/avatao/01-reverse4/first_steps.md
"r2 -A ./binaryFile", -A  flag is executing `aaa` and not `aa`
=> Fix r2 tip about '-A'

introduction/compilation_portability.md
just a simple url update for a broken link to the Dockerfile which moved from /docs to the root of the repo
=> fixing broken link to Dockerfile

esil.md
The table entries describing OR ops weren't rendered correctly since '|' was being parsed as a column delimiter. This commit just adds an escaping backslash in the entries for OR and OR EQ
=> Fix wonky table in esil.md

disassembling/esil.md
While I was reading the radare2 book I noticed this problem
in the "ESIL Instruction Set" Section https://radare.gitbooks.io/radare2book/content/disassembling/esil.html#esil-instruction-set
I fixed it by replacing the OR symbol with it's HTML entity. I also escaped the MUL operator with a backslash. Finally I added some line breaks to reduce the horizontal width of the "Operation" column to give the "example" column more space.
The end result can be seen in my fork of the repository https://github.com/Vorlent/radare2book/blob/e69e613295168f017f3d895991b9e719e3d53886/disassembling/esil.md#esil-instruction-set
PS: I said "ESIL Commands" in the commit messages but what I really meant was the "ESIL Instruction Set" Section.
=> Fix ESIL Table formatting

introduction/overview.md, rasm2/intro.md
As mentioned in #59 MSIL removed from overview and `rasm2` intro.
=> Remove MSIL from being mentioned as it's no longer supported

disassembling/esil.md
Added all supported internal flags according to `libr/anal/esil.c`
Some of them were missing from the documentation which was confusing we while I was trying to figure out how to update the `N` and `V` flags on ARM.
=> [esil] add more internal flags

introduction/expressions.md
change 
```
[0x00000000]> "? 1 | 2" 3 0x3 03 3 0000:0003 3 "\x03" 00000011 2.0 2.000000f 2.000000
```
to 
```
[0x00000000]> "? 1 | 2"
3 0x3 03 3 0000:0003 3 "\x03" 00000011 2.0 2.000000f 2.000000
```
=> Fix expression output

basic_commands/mapping_files.md
Due to some changes like this one https://github.com/radare/radare2/issues/10022 this section was not up-to-date. PR with the latest 'o' output to match the book with the tool.
=> Updated 'o' section

analysis/code_analysis.md, analysis/intro.md, basic_commands/comparing_bytes.md, basic_commands/mapping_files.md, basic_commands/seeking.md, basic_commands/types.md, configuration/evars.md, debugger/files.md, debugger/intro.md, disassembling/adding_metadata.md, disassembling/esil.md, disassembling/intro.md, first_steps/command_format.md, first_steps/history.md, first_steps/overview.md, plugins/ioplugins.md, plugins/python.md, tools/rabin2/file_identification.md, tools/rabin2/intro.md, tools/rahash2/intro.md, tools/rarun2/intro.md
This is an attempt to remove all occurrences of "etc" which doesn't add information but leaves an unnecessary feeling of incompleteness to the reader.
I tried to avoid bullshit expressions like "plus a lot more" but probably failed in some place.
=> Get rid of most “etc” occurrences

analysis/code_analysis.md, disassembling/esil.md
Fixed typos, rewording, capitalization, puntuation, markdown escaping and some terms for consistency between chapters.
=> Reviewed and fixed code_anaylsis.md and esil.md

first_steps/history.md
- There shouldn't be spaces surrounding phrases separated by dashes
- 'archs' is needlessly shortened, expanding it makes the meaning more evident
- Lots of small extra words that took away from readability and made it more confusing/difficult to parse.
I think these changes make the whole intro read a lot smoother. Let me know what you think.
=> A bunch of small changes to grammer to make it more readable

first_steps/windows_compilation.md
Additional details to Windows compilation instructions.
Updated "Compile Radare2 Code" section and added "Check That Radare2 Runs From All Locations" section. This is due to various issues run into while installing the Windows version of Radare2 for Visual Studio Community 2017. 3 issues were kept in mind.
1. When running the build command `msbuild build\radare2.sln /p:Configuration=Debug /m` for the 32-bit install, the following error kept appearing: `error MSB4126: The specified solution configuration "Debug|x86" is invalid.` A fix is provided for this error.
1. After compiling and installing the program. The PATH variable was not updated on my system. This happened for multiple installs. To help with this, the `Check That Radare2 Runs From All Locations` section is added.
1. Some …
=> Windows compilation update

refcard/intro.md, refcard/radare2_rc.tex
plus some cleanup:
* 7 visually unchanged lines in refcard/intro.md contained special multi-byte space characters
* trimmed a trailing space in refcard/radare2_rc.tex
=> improve refcard search command /x

analysis/types.md, disassembling/esil.md, scripting/intro.md
Without escapting, the closing parenthesis of a url like
`https://en.wikipedia.org/wiki/Forth_(programming_language)`
would get interpreted as the closing symbol for an inline-style link
(resulting in incorrect link target and a superfluous closing
parenthesis behind the link).
For example, see first line of [1] which shows `Forth)-like` instead of `Forth-like` and links to a non-existing Wikipedia page.
[1] https://radare.gitbooks.io/radare2book/content/disassembling/esil.html
=> Escape parenthesis in Markdown urls

first_steps/overview.md
The original version works well on Linux, but not on MacOS.
I get
```bash
$ rahash2 file -a md5
file: 0x00000000-0x000006ee sha256: 6042020f04d4b49b4f67efa49e28386a8d80a62fa65b498fabe581bb131ecc22
rahash2: Cannot open '-a'
```
on both bash and zsh.
=> rearrange command line options

analysis/variables.md
The syntax for afvn is displayed as:
```
:> afv?~afvn
| afvn [new_name] ([old_name])  rename argument/local
```
It was last changed in [this commit](https://github.com/radareorg/radare2/commit/aa435d9a5748b2513cbfd0cd295930dd50f2161a) 
On the radare2book, it is still
```
| afvn [old_name] [new_name]  rename argument/local
```
---
I'm on radare2 4.5.0,
```
radare2 4.5.0-git 24580 @ linux-x86-64 git.4.4.0-111-gd7258113d
commit: d7258113d9332dbeb1da2134d3440480e966ae6b build: 2020-05-02__22:07:31
```
=> Update variables.md: Change afvn syntax to [new_name] [old_name]

arch/8051.md
the asm.jmpsub option is apperantly outdated / enabled by default:
> \<pancake\> are you using r2 from the past?
also there's an assembler available, put that in the list.
=> remove reference to asm.jmpsub

plugins/python.md
The asm plugin example does not correctly set endianness. _endian_ should be an int as defined here:
https://github.com/radareorg/radare2-rlang/blob/master/python/asm.c#L131
https://github.com/radareorg/radare2-rlang/blob/master/python/asm.c#L18
When starting radare (`r2 -I myplugin.py -a myarch`):
`TypeError: 'str' object cannot be interpreted as an integer`
And when disassembling radare prints:
`RAsmPlugin doesn't specify endianness`
**Test plan**
Verified the arch is listed (`e asm.arch = ?`) and is disassembling (`pd 1`). Both error logs above are gone.
=> Fix Python asm plugin example.

signatures/zignatures.md
Help option of the `z` command, `z?` returned information about commands like `zq`, `zi` and `zq` which are not in the radare2book.
```
| z.           find matching zignatures in current offset
| zq           show zignatures in quiet mode
| zk           show zignatures in sdb format
| zg           generate zignatures (alias for zaF)
| zc[?]        compare current zignspace zignatures with another one
| zi           show zignatures matching information
```
I've added information about the new commands.
---
My version is :
```
radare2 4.5.0-git 24766 @ linux-x86-64 git.4.4.0-217-gd2e6b41e5
commit: d2e6b41e533aeae51d605697d7748f334f24db0c build: 2020-05-27__18:05:42
```
=> Update zignatures.md: Added information about the new commands in z

analysis/code_analysis.md
The command hints in analysis/code_analysis were a bit outdated. The hints in the current version of radare2 had more hints. 
**Changes**
Added the new command hints from latest version of radare2:
```
radare2 4.5.0-git 24785 @ linux-x86-64 git.4.4.0-232-gee9025c91
commit: ee9025c9170c15dea5e68d4d5179d41e78868493 build: 2020-06-02__15:22:18
```
=> Update command hints in code_analysis

analysis/types.md, basic_commands/block_size.md, basic_commands/comparing_bytes.md, basic_commands/seeking.md, basic_commands/types.md, basic_commands/write.md, basic_commands/yank_paste.md, configuration/colors.md, configuration/intro.md, debugger/memory_maps.md, debugger/remoting_capabilities.md, disassembling/adding_metadata.md, tools/r2pm/intro.md, tools/radiff2/intro.md, tools/rafind2/intro.md
Updated most of the outdated command hints of various radare2 commands.
**Changes**
* Updated command hints in types.md, basic_commands.md, memory_maps.md, adding_metadata,md, intro.md in configuration, remoting_capabilities.md and the help of radiff2, r2pm and rafind2.
* Added info on toggling between themes in colors.md
---
My radare2 version is : 
```
radare2 4.5.0-git 24795 @ linux-x86-64 git.4.4.0-239-g9de7c2e8d
commit: 9de7c2e8dde62c43afd098dbf22787d364950d27 build: 2020-06-04__22:25:02
```
=> Update command hints

src/SUMMARY.md, src/first_steps/compilation_android.md
Related to https://github.com/radareorg/radare2/pull/17192 .
**Test plan**
I have manually checked the explained steps and they work.
None.
=> Add howto compile on android

src/scripting/r2pipe.md
The rust example for r2pipe was throwing the following compilation error:
```
error[E0599]: no method named `pretty` found for enum `serde_json::value::Value` in the current scope
--> src/main.rs:8:23
|
8 |   println!("{}", json.pretty());
|                       ^^^^^^ method not found in `serde_json::value::Value`
error[E0599]: no method named `find_path` found for enum `serde_json::value::Value` in the current scope
--> src/main.rs:9:28
|
9 |   println!("ARCH {}", json.find_path(&["bin","arch"]).unwrap());
|                            ^^^^^^^^^ method not found in `serde_json::value::Value`
error: aborting due to 2 previous errors
```
Looks like rust r2pipe switched the json lib
from
- https://doc.rust-lang.org/1.1.0/serialize/json/enum.Json.html
to
- https://docs.serde.rs/serde_json/
=> fix r2pipe rust example (serde_json)

README.md, src/README.md, src/intro.md
Introduction page shows links in plain text at https://book.rada.re/,
it also points to the full github.io GitHub Pages URL. Both problems
are now fixed by this commit.
**Test plan**
None
None
=> Fix links from not being links when rendered by mdbook

src/basic_commands/print_modes.md
Practical example in `print_modes.md` was using outdated GStreamer libraries for demonstration. So, I took a liberty of rewriting it against another random GST plugin on my system.
Why?
- LGPL license
- belongs to gst-plugins-good, i.e. widely installed
- modern gstreamer-1.0
- uses correct `pf` flags for string pointers
- reproducible
**Test plan**
Copy-paste into your r2 shell, modify paths and offsets as needed.
None
=> Update print_modes practical example

src/basic_commands/block_size.md
`pd` operates on opcodes, `pD` operates on bytes. Later makes more sense
when talking about  block size.
Also, `bf <...>; pD @ <...>` is not an exact equivalent of `pdf`,
since `pdf` does not change block size globally -- I doubt if it takes
block size into consideration at all.
**Test plan**
None
None
=> block_size: Fix command on `bf; pd/pD` and rewording

src/first_steps/getting_radare.md
Remove from  "Downloading radare2" in radare2book any citation to http://bin.rada.re/ as it is no more used.
Official binaries are now available in Github
Nightly builds are available as artefacts in GitHub Actions  
...
**Test plan**
Regenerate radare2bool
...
=> Remove citation to http://bin.rada.re/

src/first_steps/expressions.md
=> Update expressions.md : right and left shift must be >> and <<

.github/workflows/ci.yml, .github/workflows/pandoc.yml
CI currently dies with this error on `ci.yml` and `pandoc.yml`:
```
Error: .github#L1
No event triggers defined in `on`
```
This should fix it.
=> Add trigger events for push to master in CI

README.md
Removal of pandoc.yml broke the badge, uses ci.yml now
=> Update workflow link in README

src/search_bytes/intro.md
Information about the search variables should be more prominent. They now have a subsection to clarify. Special attention given to `search.in`.
=> Improve search intro page and add search var section

src/plugins/ioplugins.md
=> Tell how to write IO plugins in the IO plugin chapter.

src/tools/rax2/intro.md
**Checklist**
Add example for base64 and clean some other example and descriptions.
=> rax2: Clean and update rax2 with base64 examples

src/disassembling/adding_metadata.md
**Checklist**
The radar2 book links to the old location of `radare2ida` which does not exist anymore.
Instead, make it should point to the new `radare2-extras/r2ida` location.
=> replace old dead link with new correct one

src/basic_commands/dietline.md
**Checklist**
Adding documentation for new features implemented in PR [#22521](https://github.com/radareorg/radare2/pull/22521)
=> Update dietline vi-mode docs

src/analysis/symbols.md
Symbol servers need to be space separated now
**Checklist**
=> Symbol servers need to be space separated now

src/search_bytes/configurating_the_search.md
**Checklist**
1. Fixed small spelling errors.
2. Added helpful example to `e search.in` option.
=> configurating_the_search.md: Fixed spelling mistakes and added examples

.github/workflows/ci.yml, Makefile, book.toml, cover.tex, metadata.yaml, src/COVER.md
1. Fix error loading images using pandoc and remove the workaround from the `Makefile`.
2. Add PDF and ePub metadata in `metadata.yaml` file.
3. Fix PDF cover
=> Fix pandoc images

.github/workflows/ci.yml, .gitignore, Makefile
Added new output to implement #345 
Implemented as a single `info` file.
Also added to releases when created.
=> Add info file support

.github/workflows/ci.yml, .gitignore, Makefile
Changed Makefile use md2gmi user install (instead of folder build).
With an error message if it is not installed:
```
ERROR: Missing md2gmi.
To install run: go install github.com/n0x1m/md2gmi@latest
```
Also added to the CI to build it and upload to each release.
=> Add build gmi to the CI

.github/workflows/ci.yml, Makefile, lint.sh, one.sh, src/analysis/syscalls.md, src/analysis/types.md, src/commandline/block_size.md, src/commandline/intro.md, src/commandline/print_modes.md, src/emulation/intro.md, src/plugins/intro.md, src/refcard/intro.md, src/signatures/zignatures.md
=> Add single markdown file target and implement markdown link linter

src/install/snap.md
Remove the PATH hack since it can introduce problems, mostly when using r2pm and external plugins.
=> Remove PATH "hack" for snap install

src/install/docker.md, src/install/flatpak.md, src/install/snap.md
Update install docs to mention the addition of _decai_ plugin and _iaito_ snap.
=> Update install docs

src/first_steps/commandline_flags.md
**Checklist**
Change 1KB -> 512B, which is the default behavior:
```
$ man radare2 | grep -i malloc://
-           Equivalent of 'r2 malloc://512'
```
```
[vagrant@fedora40 radare2]$ r2 -v
radare2 5.9.5 32531 @ linux-x86-64
birth: git.5.9.4-150-gb46f70a4bf 2024-09-14__11:34:45
commit: b46f70a4bf4240fbde26c126ce263e8ab3ecf4dc
options: gpl -O? cs:5 cl:2 make
```
=> Minor commandline_flags.md fix

src/tools/rahash2/intro.md
**Checklist**
Switch `-B 1M -b` to `-B -b 1M`, old command failed:
```
$ rahash2 -B 1M -b -a sha256 /bin/ls
ERROR: Cannot open '1M'
```
The fixed command doesn't quite behave as expected either, but created a separate issue about that: https://github.com/radareorg/radare2/issues/23371.
=> Fix broken rahash2 command in the docs

README.md, src/r2yara/intro.md
**Checklist**
Keep YARA documentation in a single file.
=> Merge yara content in a single file

src/crackmes/ioli/ioli_0x05.md
**Checklist**
- [x ] Closing issues: #issue
This fix literally fixes one word in the Crackmes section of the book. It fixes the word *odd* to *even* for second point in the password constraint list for the **IOLI 0x05** write up.
This closes issue 431 (which was specifically created by me for this fix).
=> change word 'odd' to 'even'
