radareorg/radare2-book

rabin2/entrypoints.md
rabin2/file_identification.md
rabin2/imports.md
rabin2/intro.md
rabin2/libraries.md
rabin2/program_sections.md
rabin2/strings.md
rabin2/symbols.md
radiff2/intro.md
radiff2/radiff_tool.md
rahash2/intro.md
rahash2/rahash_tool.md
rasm2/assemble.md
rasm2/disassemble.md
rasm2/intro.md
refcard/intro.md
search_bytes/automatization.md
search_bytes/backward_search.md
search_bytes/basic_searches.md
search_bytes/configurating_the_search.md
search_bytes/intro.md
search_bytes/pattern_search.md
search_bytes/search_in_assembly.md
search_bytes/searching_aes_keys.md
visual_mode/intro.md
visual_mode/visual_cursor.md
visual_mode/visual_insert.md
visual_mode/visual_xrefs.md

More or less everything of those small things that I wanted to fix in current radare2book.

The final bunch of style and language corrections for the rest of chapters

---

basic_commands/print_modes.md
basic_commands/sections.md
basic_commands/write.md
basic_commands/zoom.md
configuration/intro.md
disassembling/adding_metadata.md
esil.md
introduction/contributing.md
introduction/getting_radare.md
introduction/history.md
introduction/overview.md

I've done some rewording and grammar changes in the introduction paragraphs.
Also, I've made some whitespace changes because some parsers need it to work properly.

Enhance Readability / Other Fixes

---

esil.md

reality update

---

esil.md

Fixed condition esil operator description

---

basic_commands/types.md

the good thing is that while writing this I found a bug at types xD

adding a page on types

---

analysis/code_analysis.md
basic_commands/mapping_files.md
basic_commands/print_modes.md
basic_commands/seeking.md
basic_commands/types.md
configuration/common_configuration_variables.md
configuration/intro.md
crackmes/avatao/01-reverse4/main.md
crackmes/avatao/01-reverse4/vmloop.md
debugger/intro.md
disassembling/adding_metadata.md
esil.md
introduction/basic_debugger_session.md
introduction/basic_usage.md
introduction/expressions.md
introduction/windows_compilation.md
rasm2/intro.md
remoting_capabilities.md
visual_mode/visual_disassembly.md

Fixed classics such as readed, substraction, accordingaly, automatoc and various misspellings of disassembling :)

I fixed a spelling error and I liked it

---

esil.md

Hopefully explains the concepts and env variables associated with ESIL a bit better.

Rewrote parts of esil description

---

introduction/expressions.md

https://github.com/radare/radare2/issues/6658#issuecomment-277255768

Fix explanation on quoting logical OR

---

configuration/intro.md

https://github.com/radare/radare2/issues/6657#issuecomment-277255616

Add note on using =? for exploring config

---

rahash2/intro.md

We now use `ph` command instead of `#`.

Updating hashing inside r2 session

---

introduction/rax2.md

Updated randomart command line switch example (-K instead of -k).
Updated -h output.

Updated command line switches

---

ragg2/ragg2.md

update ragg2 book

---

refcard/intro.md

afaik "Content Cell" is not a radare2 command

Refcard removed slip-up

---

basic_commands/mapping_files.md

https://github.com/radare/radare2/commit/e74aadad287edf94efb22c1210be66a100f57168

update `o?` menu to latest commit

---

debugger/migration.md

Added commands for WinDbg in the Migration Table.

Added Windbg reference in Migration

---

basic_commands/seeking.md

Reading the book currently and just noticed this little grammar mistake.

Fixed English grammar and punctuation.

---

SUMMARY.md
arch/8051.md
arch/intro.md

Added new section "Architectures" for architecture specific chapters.
Added chapter for 8051.

Added arch section and 8051 chapter

---

disassembling/esil.md

The variable name was changed on https://github.com/radare/radare2/commit/cd7d7315d6f8d04a2794cc78d41486b2183d6630

Use the new syntax for asm.emustr

---

arch/8051.md

minor update to 8051 documentation

8051: aei required after setting cpu

---

visual_mode/intro.md

In particular I noticed b/B have changed

Update Visual mode help in intro.md

---

arch/8051.md

Added information about how overlapping memory areas are handled.

8051 update

---

SUMMARY.md
analysis/graphs.md
analysis/intro.md

Added the section explaining a bit more in detail how ag* graph commands work

Added graph commands section

---

configuration/intro.md

The correct option to disable load .radare2rc should be -N

fix command option

---

analysis/code_analysis.md
analysis/emulation.md
analysis/graphs.md

In the following days I hope to go over the entire book and fix/improve:

[WIP] Grammar time

---

analysis/intro.md
analysis/symbols.md
analysis/types.md
analysis/variables.md
analysis/vtables.md

Grammar time: intro.md, symbols.md, types.md, variables.md, vtables.md

---

basic_commands/print_modes.md
basic_commands/sections.md
basic_commands/seeking.md
basic_commands/types.md
basic_commands/write.md
basic_commands/yank_paste.md
basic_commands/zoom.md

Grammar time: print_modes.md, sections.md, seeking.md, types.md, write.md, yank_paste.md, zoom.md

---

first_steps/basic_debugger_session.md
first_steps/command_format.md
first_steps/intro.md

I'm just starting out with radare2, and it looks awesome. Wanted to touch up the book a bit to make it easier for the next guy to learn from.

Small grammar and proofreading fixes

---

first_steps/windows_compilation.md

I did not check if those were working, if anyone can check on a VM before merging it'd be great.

Updated windows compilation instructions

---

analysis/graphs.md

This should be merged only after (and if) https://github.com/radare/radare2/pull/10860 gets merged to r2

Updated "Graph commands" section of analysis

---

analysis/graphs.md

Sorry didn't notice your message.
Reverts radare/radare2book#139

Revert "Updated "Graph commands" section of analysis"

---

plugins/python.md

see https://github.com/radare/radare2-bindings/pull/209

python-bindings: fix analysis api

---

basic_commands/write.md

One particular example did not have any explanation. So I added it and made a pr

Added explanation to the woe example in write.md

---

analysis/types.md

Update tl command

---

scripting/intro.md

Based on from https://github.com/radare/radare2/pull/14369

Added sort, join and uniq

---

basic_commands/dietline.md

Updated the emacs commands as well

Added documentation for vi mode on dietline

---

analysis/syscalls.md
search_bytes/search_in_assembly.md
search_bytes/searching_aes_keys.md

https://github.com/radare/radare2/commit/4e079c4b8575f6a0744bc945ca2d4261f16cea74

some search fixes from

---

analysis/code_analysis.md
analysis/types.md

Updating this after https://github.com/radare/radare2/pull/14966 got merged.

Changes related to "ta" commands

---

scripting/macros.md

Related to https://github.com/radareorg/radare2/pull/16179
...
**Test plan**
Check if all the commands listed in the page still work.

Update macros.md to use ; instead of ,

---

debugger/migration.md

Replaced "thru" with "through"
**Test plan**
I googled  through and it's spelled correctly.
Can't think of any.

Fixed typo

---

SUMMARY.md
debugger/windows_messages.md

Fix #222 - Document dW, dbW and dWi

---

tools/rasign2/intro.md

This is an attempt to add documentation for the rasign2 tool. I am not confident I understand how the book is generated from this code. I figured this would be a good start though. Let me know if you don't like it, I am not the best at technical writing. I am happy to receive suggestions.
**Test plan**
....
closes #244

add rasign2 documentation

---

.gitignore
src/analysis/variables.md
src/debugger/intro.md
src/visual_mode/visual_panels.md

* Added command hints for `doc` and `doof`
* Added documentation about Visual tabs. Fixes #183 
My radare2 version:
```
radare2 4.5.0-git 24888 @ linux-x86-64 git.4.4.0-328-gcff5ec573
commit: cff5ec5736fc6fa33fc8bc3ea4b2c7e26e9603ac build: 2020-06-24__21:56:49
```

 Added documentation for Visual tabs

---

src/scripting/macros.md

Added basic documentation for aliases.
Related to #173

Update macros.md: Add documentation about alias

---

.proselint/proselint/config
.travis.yml
src/analysis/symbols.md
src/basic_commands/print_modes.md
src/crackmes/avatao/01-reverse4/intro.md
src/crackmes/avatao/01-reverse4/main.md
src/crackmes/avatao/01-reverse4/radare2.md
src/crackmes/avatao/01-reverse4/vmloop.md
src/crackmes/ioli/ioli_0x00.md
src/debugger/files.md
src/plugins/intro.md
src/refcard/intro.md
src/search_bytes/basic_searches.md
src/signatures/zignatures.md
src/tools/rafind2/intro.md
src/tools/rahash2/intro.md
src/visual_mode/intro.md

This should fix proselint issues.

Added proselint config

---

src/analysis/code_analysis.md

Added information about  `e anal.in` as advised in Issue [#17236](https://github.com/radareorg/radare2/pull/17236)
**Test plan**
* Review and make sure that the given information is correct
Issue [#17236](https://github.com/radareorg/radare2/pull/17236)

Update information about e anal.in

---

src/basic_commands/flags.md

Added a short documentation for setting up a flag zone.
**Test plan**
Closes #192

Document flagzones

---

src/analysis/graphs.md
src/basic_commands/print_modes.md
src/visual_mode/visual_panels.md

* Updated command hints in `graphs.md` and `print_modes.md`.
* Added information about new valid print code formats for human-readable languages in `print_mods.md`
* Added information about the 'v' command in visual panels.

Update command hints and information about pc command

---

src/analysis/syscalls.md
src/configuration/evars.md

* Added an example about `dcs` - Issue #140 
* Added documentation about `asm.sub.reg` -  Issue #190 
Closes #190

Document asm.sub.reg and improve Syscalls

---

src/analysis/code_analysis.md
src/configuration/evars.md

* Added a short description and an example for the `axtg` command
* Added information about some useful evars.
None

Document `axtg` command

---

src/analysis/code_analysis.md

* Document `axg` and `axg*`
**Test plan**
Closes #172

Document `axg` command

---

src/signatures/zignatures.md

This brings information up to date for when the `zbr` command is added. See this [PR](https://github.com/radareorg/radare2/pull/17467)
**Test plan**
My technical writing skills are not great. While the information should be accurate it may not be clear. Feel free to suggest changes or modify.
...

add info for zb commands

---

src/analysis/calling_conventions.md

* Updated the command hints under `afc?` in Calling Conventions.
**Test plan**
None
None

Update command hints under `afc`

---

src/debugger/windbg.md

* Add instructions on how to set up and connect to a KDNet interface
* Reformat the guide
radareorg/radare2#17340

Add info for KDNet interface

---

src/debugger/windbg.md

For https://github.com/radareorg/radare2/pull/17491

Document new `windbg` plugin and `winkd` rename

---

src/analysis/code_analysis.md

fix typo and update usage of `af?`
1. fix typo 4 important program wide half-automated analysis commands to 5: `aab`, `aac`, `aaf`, `aar`, `aad`.
2. update usage of af list ( radare2 `4.6.0-git 25118` version)
using command `af?` in  `4.6.0-git 25118` version.
...
**Test plan**
...
...

fix typo and update `af?` usage

---

src/signatures/zignatures.md

1. Zign variables were a bit out of date and lacked full help information
2. [This](https://github.com/radareorg/radare2/pull/17545) PR will add the `zign.bestthres` variable. Unless it is changed before merging.
I will update this PR if anything changes in the r2 PR I mentioned.
**Test plan**
...
...

Update zign variables

---

src/basic_commands/dietline.md

* Restructured the dietline chapter to organize the list of the hotkeys under titles.
**Test plan**
Closes #270

Restructure dietline chapter

---

src/debugger/heap.md

This is the book documentation of  the PR thttps://github.com/radareorg/radare2/pull/17534

Add glibc 2.32 instructions ##17534

---

src/analysis/code_analysis.md

The current version of the book doesn't explicitly talk about `afl`. Here, I've added an explanation for that and for a couple of commands that come under `afl`.
I've also added a title 'Analyze functions'
**Test plan**
None

Document `afl` with an explanation

---

src/crackmes/ioli/ioli_0x02.md

A radare2 writeup for crackme_0x02 of ioli

Ioli crackme 0x02

---

src/analysis/emulation.md
src/disassembling/esil.md

minor edits to fix esil-related part

some minor edits to esil related part

---

src/visual_mode/visual_panels.md

Added a short explanation about how to save a visual panel layout and about how to open a saved one.
**Test plan**
None

Document about saving visual panel layouts

---

src/first_steps/compilation_portability.md

https://github.com/radareorg/radare2/issues/17958
**Test plan**
...
...

Update meson build

---

src/first_steps/history.md

Fix confusing wording

---

LICENSE

The commit message of e45b1da51e60758c8347b415b51ab852a0add19d says CC-BY-SA was intended, but the text was wrong.
**Test plan**
...
...

Fix license: CC-BY-SA 4.0

---

src/disassembling/esil.md

Add the ~, ~/, and ~% operators to the docs. They are respectively sign extension, signed integer division, and signed modulus.

add the sign ext operator + signed div / mod

---

src/basic_commands/print_modes.md

Header did not render properly. And of course — why would it?
**Test plan**
Visit https://book.rada.re/basic_commands/print_modes.html.
None.

Remove weird control character at the beginning of md file

---

src/configuration/charset.md

Document the commands e `cfg.charset=pokered`; and  e `dir.charset=pokered`;.
...
**Test plan**
...
closes #307 
...

Add documentation to custom charset doc

---

src/disassembling/esil.md

Update esil chapter a bit

---

src/search_bytes/basic_searches.md

Add section and masked search.

Add masked search

---

.github/workflows/mdbook.yml

Add pandoc step

---

src/search_bytes/pattern_search.md

Add section about delta search

---

src/plugins/python.md

**Checklist**
Documentation how to use archinfo in Python anal plugins.

Document archinfo bit for Python anal plugins

---

src/configuration/charset.md
src/plugins/dev-charset.md

Tell how to write charset plugin doc

---

src/plugins/dev-charset.md

**Checklist**
Use markdown lists to layout the steps

Use markdown lists to layout the steps

---

src/SUMMARY.md
src/basic_commands/cmp_watchers.md

Book changes for the `cw` refactor at radareorg/radare2#19889

Document and provide examples for the `cw` command

---

.github/workflows/ci.yml
.gitignore
Makefile

Also added r2book.epub and r2book.pdf to the gitignore

Add pdf and epub targets to make all and use it in the CI

---

src/crackmes/ioli/ioli_0x02.md

**Checklist**
I've fixed the typo error in one of the crack-me walkthroughs

typo-fix-1

---

src/tools/ragg2/ragg2.md

**Checklist**
This PR describes ragg2 and its options better along with examples - partially satisfies https://github.com/radareorg/radare2-book/issues/216.
Thanks,
Adwaith

ragg2 documentation updated

---

src/search_bytes/searching_crypto.md

**Checklist**
Update documentation to reflect the changes in https://github.com/radareorg/radare2/commit/c53b680c7a3cbdda5bf639c04309f8870ea618e5

Update documentation for expanded key search

---

src/debugger/remote_gdb.md

**Checklist**
Remove `=g!` from documentation after https://github.com/radareorg/radare2/pull/21237
Explain how to see GDB messages using log level.

Explain how to debug GDB protocol after removing =g!

---

src/visual_mode/visual_assembler.md

**Checklist**
Changed the path of the image.

Fixed inability to display images.

---

src/basic_commands/intro.md

Elaborate on the C function called

---

src/configuration/evars.md

Fix typo "psuedo" -> "pseudo"

---

src/analysis/emulation.md

**Checklist**
Improved the grammar, punctuation, and clarity of section 8.7: Emulation

Improve grammar and clarity of section 8.7: Emulation

---

src/tools/ragg2/ragg2.md

Remove raw bytes causing text to fail in the the ragg2 example

---

src/plugins/r2frida.md

**Checklist**
Adds basic usage examples for common r2frida tasks. I'll follow up with more.

Add some basic r2frida usage examples

---

src/search/searching_crypto.md

**Checklist**
Documentation of the `/h` command.

Document hash search

---

src/r2frida/first_steps.md

**Checklist**
A small typo fix.

Fix typo in first steps for r2frida

---

src/search/pattern_search.md

**Checklist**
Add documentation for magic pattern search.

Add magic pattern search

---

src/SUMMARY.md
src/commandline/flags.md
src/r2yara/intro.md

Initial commit for r2yara documentation

---

src/r2wars/intro.md

Initial r2wars chapter

---

src/SUMMARY.md
src/r2fwrev/intro.md

Initial firmware reversing chapter

---

src/r2wars/intro.md

fixing minor typos and adding a link to a great writeup

some fixes for r2wars

---

src/commandline/write.md

Fix wb documentation

---

src/r2yara/rules_generator.md

**Checklist**
Add the documentation `yrg` group of commands.

Add r2yara generartor section

---

src/r2yara/intro.md

Update r2yara default rule folder

---

src/r2yara/intro.md

Fixed a typo: "r2frida" -> "r2yara"

---

src/config/colors.md

**Checklist**
Adding information on how to create themes from own experience and Advent 2024.

Updating theme creation infos

---

src/tools/intro.md

"rest if chapters" -> "rest of chapters"

fix: correct a typo

---

src/install/build.md

**Checklist**
Fixing a typo in the install instructions.

Fix typo in install instructions

---

src/analysis/graphs.md

**Checklist**
This pull request updates `src/analysis/graphs.md`:
- adds a new section describing the `agfm` command for generating Mermaid diagrams.
- fixes some typos and improves phrasing for better readability.

Update graphs.md to include mermaid

---

src/config/files.md
src/config/intro.md

**Checklist**
Changed RC files path as for radareorg/radare2@0205fc0

Changed documentation on configuration files reflecting commit radareorg/radare2@0205fc0

---

src/SUMMARY.md
src/plugins/r2ai.md

Add a chapter on r2ai
